trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
# https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/docker?view=azure-devops
- task: Docker@2
  inputs:
    containerRegistry: 'Docker Hub engswee'
    repository: 'engswee/flashpipe'
    command: 'buildAndPush'
    Dockerfile: 'src/main/docker/Dockerfile'
    buildContext: '.'
    tags: 1.0.2  # FLASHPIPE_VERSION